version: '3'
services:
  mysql:
   container_name: db-mysql
   build: ./docker/mysql
   environment:
    MYSQL_DATABASE: exportasimple
    MYSQL_USER: exporta-db
    MYSQL_PASSWORD: exporta_pass
    MYSQL_ROOT_PASSWORD: exporta
    MYSQL_ROOT_HOST: '%'
   expose:
    - "3306"
   ports:
   - "3306:3306"
   restart: always
   networks:
    static-network:
      ipv4_address: 172.23.0.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.23.0.0/16
